DROP TABLE IF EXISTS moisture_readings;
DROP TABLE IF EXISTS water_events;

CREATE TABLE moisture_readings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    channel INTEGER NOT NULL,
    value REAL NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE water_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    seconds INTEGER NOT NULL,
    zone INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
